# Generated by Django 5.0.6 on 2025-09-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='terms_and_condition',
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='operating_system',
            field=models.CharField(blank=True, choices=[('ubuntu_22_04_server', 'Ubuntu 22.04 Server'), ('ubuntu_24_04_server', 'Ubuntu 24.04 Server'), ('ubuntu_22_04_desktop', 'Ubuntu 22.04 Desktop'), ('ubuntu_24_04_desktop', 'Ubuntu 24.04 Desktop'), ('windows_server_2019', 'Windows Server 2019'), ('windows_desktop', 'Windows Desktop')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('telebirr', 'Telebirr')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tin_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
