# Generated by Django 5.0.6 on 2025-09-25 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-issue_date']},
        ),
    ]
