# Generated by Django 5.0.6 on 2025-09-25 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_invoice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-issue_date']},
        ),
    ]
