# Generated by Django 5.0.6 on 2025-09-26 11:10

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20250926_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='hourly_price',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='quarterly_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='semi_annual_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='yearly_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi-annual', 'Semi-Annual'), ('yearly', 'Yearly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi-annual', 'Semi-Annual'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_set', to='core.customer'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 26, 11, 10, 23, 316159, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='data_storage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='os_storage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_currency',
            field=models.CharField(default='ETB', max_length=3),
        ),
    ]
