# Generated by Django 5.0.6 on 2025-10-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='additional_data_storage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
