# Generated by Django 5.0.6 on 2025-10-01 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_cartitem_additional_data_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='additional_data_storage',
        ),
    ]
