# Generated by Django 5.0.6 on 2025-10-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_cartitem_additional_data_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='additional_data_storage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='additional_data_storage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='data_storage_price_per_gb',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=12),
        ),
    ]
