# Generated by Django 5.0.6 on 2025-10-01 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_cartitem_additional_data_storage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='additional_data_storage',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='additional_data_storage',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='data_storage_price_per_gb',
        ),
    ]
