# Generated by Django 5.0.6 on 2025-10-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_cartitem_additional_data_storage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='additional_storage',
            field=models.PositiveIntegerField(default=0, help_text='Additional storage in GB'),
        ),
    ]
