# Generated by Django 5.0.6 on 2025-10-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_cartitem_additional_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='additional_storage',
            field=models.PositiveIntegerField(default=0, help_text='Additional storage in GB'),
        ),
    ]
