# Generated by Django 5.0.6 on 2025-10-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_subscription_additional_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='additional_storage',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='additional_storage',
        ),
    ]
