# Generated by Django 5.0.6 on 2025-10-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_cartitem_additional_storage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='additional_storage',
            field=models.IntegerField(blank=True, default=0, help_text='Additional storage in GB'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='additional_storage',
            field=models.IntegerField(blank=True, default=0, help_text='Additional storage in GB'),
        ),
    ]
