# Generated by Django 5.0.6 on 2025-10-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_cartitem_additional_storage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='additional_storage',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='additional_storage',
        ),
        migrations.AddField(
            model_name='subscription',
            name='data_storage',
            field=models.IntegerField(default=0, help_text='Custom data storage in GB for this subscription'),
        ),
    ]
