# Generated by Django 5.0.6 on 2025-10-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_cartitem_additional_storage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='data_storage',
            field=models.IntegerField(default=0),
        ),
    ]
