# Generated by Django 5.0.6 on 2025-10-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_subscription_data_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='data_storage',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='data_storage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='ram',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='vcpu',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
