# Generated by Django 5.0.6 on 2025-10-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_subscription_data_storage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='data_storage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='ram',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscription',
            name='vcpu',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
