# Generated by Django 5.0.6 on 2025-10-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_subscription_data_storage_subscription_ram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='data_storage',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='vcpu',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='data_storage',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='vcpu',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='extra_ram',
            field=models.PositiveIntegerField(default=0, help_text='Additional RAM in GB'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='extra_storage',
            field=models.PositiveIntegerField(default=0, help_text='Additional storage in GB'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='extra_vcpus',
            field=models.PositiveIntegerField(default=0, help_text='Additional vCPUs requested'),
        ),
    ]
