# Generated by Django 5.0.6 on 2025-10-02 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_cartitem_data_storage_remove_cartitem_ram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='extra_ram',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='extra_storage',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='extra_vcpus',
        ),
    ]
