# Generated by Django 5.0.6 on 2025-10-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_cartitem_extra_ram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='additional_storage',
            field=models.IntegerField(default=0, help_text='Additional storage in GB'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='additional_vcpus',
            field=models.IntegerField(default=0, help_text='Additional vCPUs'),
        ),
    ]
