# Generated by Django 5.0.6 on 2025-10-02 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_cartitem_additional_storage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='additional_storage',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='additional_vcpus',
        ),
    ]
