# Generated by Django 5.0.6 on 2025-10-02 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_cartitem_additional_storage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='add_volume',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='additional_data_storage',
            field=models.IntegerField(default=0, help_text="Additional data storage in GB beyond the plan's default data storage.", validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='orders',
            name='additional_data_storage',
            field=models.IntegerField(default=0, help_text="Additional data storage in GB beyond the plan's default data storage.", validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='subscription',
            name='additional_data_storage',
            field=models.IntegerField(default=0, help_text="Additional data storage in GB beyond the plan's default data storage.", validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
