# Generated by Django 5.0.6 on 2025-10-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_orders_add_volume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='additional_data_storage',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='additional_data_storage',
        ),
        migrations.AddField(
            model_name='orders',
            name='add_volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='additional_data_storage',
            field=models.IntegerField(default=0),
        ),
    ]
