# Generated by Django 5.0.6 on 2025-10-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_orders_additional_data_storage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='additional_data_storage',
        ),
    ]
