# Generated by Django 5.0.6 on 2025-10-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_cartitem_additional_data_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='additional_data_storage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='additional_data_storage',
            field=models.IntegerField(default=0),
        ),
    ]
